channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyter=1.0.0
  - pandas=0.24.1
  - nbgrader=0.5.5
  - scikit-learn=0.21.2
  - matplotlib=3.1.1
  - category_encoders=1.3.0
  - m2-base=1.0.0
