channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.1.2
  - mlxtend=0.17.0
  - numpy=1.17.3
  - pandas=0.25.3
  - python=3.7.3
  - python-dateutil=2.8.1
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - nbgrader==0.6.0
  - pip:
    - ml-metrics==0.1.4
